FROM ubuntu:latest

MAINTAINER Akash Subramanian <skythelimit.96@gmail.com>

RUN apt-get upgrade -y && \
    apt-get update -y && \
    apt-get install -y haproxy

CMD ["echo", "Container successfully running!"]
